// DO NOT EDIT. This file is generated by Fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $_metodologias_kanban from "./routes/(metodologias)/kanban.tsx";
import * as $_metodologias_lean from "./routes/(metodologias)/lean.tsx";
import * as $_metodologias_scrum from "./routes/(metodologias)/scrum.tsx";
import * as $_metodologias_xp from "./routes/(metodologias)/xp.tsx";
import * as $_404 from "./routes/_404.tsx";
import * as $_app from "./routes/_app.tsx";
import * as $_layout from "./routes/_layout.tsx";
import * as $ejemplos from "./routes/ejemplos.tsx";
import * as $formulario from "./routes/formulario.tsx";
import * as $index from "./routes/index.tsx";
import * as $inicio from "./routes/inicio.tsx";
import * as $privacidad from "./routes/privacidad.tsx";
import * as $FormularioI from "./islands/FormularioI.tsx";
import * as $Inicio from "./islands/Inicio.tsx";
import type { Manifest } from "$fresh/server.ts";

const manifest = {
  routes: {
    "./routes/(metodologias)/kanban.tsx": $_metodologias_kanban,
    "./routes/(metodologias)/lean.tsx": $_metodologias_lean,
    "./routes/(metodologias)/scrum.tsx": $_metodologias_scrum,
    "./routes/(metodologias)/xp.tsx": $_metodologias_xp,
    "./routes/_404.tsx": $_404,
    "./routes/_app.tsx": $_app,
    "./routes/_layout.tsx": $_layout,
    "./routes/ejemplos.tsx": $ejemplos,
    "./routes/formulario.tsx": $formulario,
    "./routes/index.tsx": $index,
    "./routes/inicio.tsx": $inicio,
    "./routes/privacidad.tsx": $privacidad,
  },
  islands: {
    "./islands/FormularioI.tsx": $FormularioI,
    "./islands/Inicio.tsx": $Inicio,
  },
  baseUrl: import.meta.url,
} satisfies Manifest;

export default manifest;
